export global Theme {
    out property <color> background-dark: #313338;
    out property <color> background-sidebar: #2b2d31;
    out property <color> background-rail: #1e1f22;
    out property <color> accent: #10b981; // Teal
    out property <color> text-primary: #dbdee1;
    out property <color> text-header: #f2f3f5;
    out property <color> text-muted: #949ba4;
    out property <color> divider: #3f4147;
}
